[project]
name = "vision-language-clothing-retrieval"
version = "0.1.0"
description = "Vision-language system for clothing retrieval"
authors = [
    { name = "Vladimir Mandić" },
    { name = "Radenko Nikolić" },
    { name = "Milica Tošić" }
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = ["torch (>=2.13.0,<3.0.0)", "numpy (>=2.5.1,<3.0.0)", "torchvision (>=0.28.0,<0.29.0)", "transformers (>=5.14.1,<6.0.0)", "matplotlib (>=3.11.1,<4.0.0)", "pandas (>=3.0.5,<4.0.0)", "fastapi (>=0.141.1,<0.142.0)", "uvicorn (>=0.52.4,<0.53.0)", "python-multipart (>=0.0.32,<0.0.33)"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "black (>=26.5.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "jupyter (>=1.1.1,<2.0.0)",
    "setuptools (>=83.0.0,<84.0.0)"
]

[tool.poetry]
packages = [
    { include = "vision_language_clothing_retrieval", from = "src" }
]

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"


[tool.poetry.dependencies]
torch = {source = "pytorch"}
torchvision = {source = "pytorch"}
[tool.black]
line-length = 100
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 100
